### PR TITLE
fix: Page rendering stripped up <style> tag #1352

### PR DESCRIPTION
**Pull request by regevbr**
fix: #1352

### CODE REVIEW

**Comment by regevbr** [comment]
Adding <style> to templates in vue is not allowed and results in the following warning
```html
Templates should only be responsible for mapping the state to the UI. Avoid placing tags with side-effects in your templates, such as <style>, as they will not be parsed.
```
And the removal of the style from the resulting html.

I managed to find a solution [here](https://stackoverflow.com/a/57331310/2242402):
in the html render we need to replace the style tags with component:
```javascript
    output = output.replace(/<style/g, `<component is="style"`);
    output = output.replace(/<\/style>/g, `</component>`);
```

**Comment by regevbr** [comment]
I actually need to use a dom manipulation so I won't change free text by accident

**Comment by regevbr** [comment]
I used cheerio to safely replace the style elements with component ones.
In order for it to work though, I had to add the `component` element as a safe one to the html-security module.
In order to prevent a misuse of the `component` I added a validation hook that will only allow `component` when it is used as a style element.

The following example:
```markdown
# H1
<style >
.sdf {
   background-color: black;
}
</style>

<component is="h2">
.sdf {
   background-color: black;
}
</component>

<component>
.sdf {
   background-color: black;
}
</component>

sdfsdf
{ .sdf }
```

Will safely compile to:
```html
<h1 class="toc-header" id="h1"><a href="#h1" class="toc-anchor">¶</a> H1</h1>
<component is="style">
.sdf {
   background-color: black;
}
</component>
<p class="sdf">sdfsdf</p>
```

Which will be rendered by vue as:
```html
<div><h1 id="h1" class="toc-header"><a href="#h1" class="toc-anchor">¶</a> H1</h1>
 <style>
.sdf {
   background-color: black;
}
</style>
 <p class="sdf">sdfsdf</p></div>
```

**Comment by regevbr** [comment]
@NGPixel can you please CR?

**Comment by regevbr** [comment]
@NGPixel while you are merging simple PRs would you mind handling this one as well 🙏?

**Comment by NGPixel** [comment]
I see what you're trying to do, but the plan is to have 2 new permission scopes to add scripts and styles from the Page Properties dialog. They will live in the `extra` json field of the page and be rendered outside of the vue instance.

**Comment by regevbr** [comment]
Ok that makes sense.
Until the plan will come together, you don't want to enable custom css per page like I implemented it? If so I will close the PR.
I think we can start by allowing my PR and when the big plan is implemented, we can disable it and force the css to be injected in the page properties...
Thoughts?

**Comment by regevbr** [comment]
@NGPixel I see that you implementer the page js and css features, awesome!
I didn't see that you added the permissions to the admin page yet am I right?

**Comment by NGPixel** [comment]
They were added here: https://github.com/Requarks/wiki/blob/83b83a7510007a58d66aeba0c556ca28151712ee/client/components/admin/admin-groups-edit-permissions.vue#L83-L95

**Comment by regevbr** [comment]
Oh my bad... Awesome work!

**Pull request closed without merging**
