### PR TITLE
Add strings to admin pages

### PR DESCRIPTION
**Pull request by Justman10000**
New strings might need to be added to the translation project...

### CODE REVIEW

**Comment by Justman10000** [comment]
@NGPixel 

Why don't you merge this if you're already renaming it?

**Comment by NGPixel** [comment]
There are several issues with your PR:

- Changes are to entire files instead of just the specific lines where strings need to be replaced.
- Many strings don't exist in Lokalise and would need to be created. This would require some work on my side and this is not the priority right now.
- The localization string names don't follow the camelCase format used elsewhere in the project.
- The modification to dev/index.js shouldn't be included in this PR. This bug was fixed recently and removing the call is not the right way to do it.
- You modify admin views that are unfinished and not user-accessible (editors, logging and webhooks). These shouldn't be included in the PR.

**Comment by Justman10000** [comment]
@NGPixel

**Comment by NGPixel** [comment]
Your PR has many issues I listed earlier and your responses to them don't make sense.

Formatting and key naming are wrong. It's not a matter of whether it works or not on your machine.

The main issue still remains that this PR only addresses half of the work needed to support localization. All the strings still need to be created, tagged, described and translated which is a very long task. This is really not the priority right now.

Thanks for the work you've put in but I don't see this PR being merged anytime soon for all the reasons listed above.

**Comment by Justman10000** [comment]
@NGPixel

What if I could help add it?

**Comment by Justman10000** [comment]
Though I thought all the strings would be automatically added to Lokalise...

**Pull request closed without merging**
