### PR TITLE
Collapsable Regions and Pasting Images

### PR DESCRIPTION
**Pull request by dmc6297**
1. Create a collapsable region

```
<markdown collapsable title="my image.png" type="Image">
</markdown>
```

2. Allow pasting of images. Converted to base64 and embedded into markdown as ``````

### CODE REVIEW

**Comment by R0Wi** [comment]
I tested this feature and it works great, thank you @dmc6297 !

https://github.com/requarks/wiki/assets/19730957/9a0f850d-6868-4560-8be3-cd7b87740979

Maybe the code in the area of https://github.com/requarks/wiki/pull/6551/files#diff-6572222f98358241abe369388929bd7692fc070e1ef397ec605ee31f83f984d0R684 could be refactored a little bit for better readability. But from a functional point of view this is exactly what people need in https://github.com/requarks/wiki/pull/5441. Hope some of the maintainers will find some time soon to review this :rocket:

**Review by Divy0007 — APPROVED** [review]

**Comment by NCDemonic** [comment]
I understand that you may have little time to develop 3.X or to maintain the current 2.x. 
But on the other hand, if you are the only maintainer why don't you accept an additional maintainer, at least for the 2.x version.

All information I can get is the blog posts which are older than one year for version 3.x. I see a lot of PRs for the 2.X version where users address and implement important usability features, but there is no comment or review from the project maintainer.

So as an administrator which is asked whether we can use this project or not - everything looks as an abandoned project where no issues get fixed. So I canot recommend using it, because there maybe security issued not being fixed.

Just a final note: Not maintaining the current version will make development of a version 3 obsolete if there are no more users left because of issues not beeing addressed, especially if the community provides fixes and PRs which are not brought upstream.

**Comment by BPowell76** [comment]
> I understand that you may have little time to develop 3.X or to maintain the current 2.x. But on the other hand, if you are the only maintainer why don't you accept an additional maintainer, at least for the 2.x version.
> 
> All information I can get is the blog posts which are older than one year for version 3.x. I see a lot of PRs for the 2.X version where users address and implement important usability features, but there is no comment or review from the project maintainer.
> 
> So as an administrator which is asked whether we can use this project or not - everything looks as an abandoned project where no issues get fixed. So I canot recommend using it, because there maybe security issued not being fixed.
> 
> Just a final note: Not maintaining the current version will make development of a version 3 obsolete if there are no more users left because of issues not beeing addressed, especially if the community provides fixes and PRs which are not brought upstream.

This is an open source project. You are free to fork your own version and make whatever changes you want. I have been waiting on a couple of PRs I made to get accepted, but I can still use the program as is.

Being a prick about things won't help so I would chill out if I were you.

**Comment by NCDemonic** [comment]
I already use a custom build version with a lot's of changes taken out of the open PRs or posts from the internet.

But if you search for specific issues and find either post that say "will be available in version 3" or you find PRs that do not get any review since years (!) - the maintainer should ask himself what the plan is for this project... Or at least should be prepared for users asking exactly this.

We have no doubt that WikiJS is a great project, but it looks like that contributions are not welcome and there won't be a new version. And that  makes me sad.

@BPowell76 BTW there is no need to use offensive language. Keep it technical

**Comment by NCDemonic** [comment]
@BPowell76 So you want to tell me, that this project is running fine the way it does? 

We can continue our discussion in a year when your PR is still open and the fix for 1292 is still not upstream

**Pull request closed without merging**
