### PR TITLE
Solving problem with foreing key contraint when page have comments #2078

### PR DESCRIPTION
**Pull request by higortavares**

### CODE REVIEW

**Comment by regevbr** [comment]
You should undo all the styling changes as they are not a real part of the fix and they don't conform with the code style of the project.

**Comment by higortavares** [comment]
> You should undo all the styling changes as they are not a real part of the fix and they don't conform with the code style of the project.

Ok. this is because my text editor

**Comment by regevbr** [comment]
I'm wondering what happens if there are multiple ids that get deleted... Not sure that is a feasible scenario currently but we should defiantly handle it as well

**Comment by higortavares** [comment]
> I'm wondering what happens if there are multiple ids that get deleted... Not sure that is a feasible scenario currently but we should defiantly handle it as well

I thought about smooth deletion, but that would cause another problem because the page has a unique key constraint

**Comment by regevbr** [comment]
Why not delete all the comments of all the pages being deleted?

**Comment by NGPixel** [comment]
Change target branch to `dev` for this PR.

**Comment by higortavares** [comment]
> Change target branch to `dev` for this PR.

ok

**Pull request closed without merging**
