### PR TITLE
fix: no markdown support for underline #2072

### PR DESCRIPTION
**Pull request by regevbr**
fix: #2072 
Add support for underline in markdown by using `++underline++`.
This fix will also show up in the editor

### CODE REVIEW

**Comment by NGPixel** [comment]
2 things to improve:

- Make it optional by adding a toggle as part of the Markdown Core module. Since this is not compliant with the CommonMark specification, it shouldn't be mandatory.

- Avoid adding a new npm dependency for just [10 lines of code](https://github.com/arve0/markdown-it-underline/blob/master/index.js). Include the code directly.

**Comment by regevbr** [comment]
Thanks @NGPixel for the comments.

I didn't use the library I mentioned in the issue as it will conflict with the current behavior of `_sdf_` so I used a different one - `markdown-it-plugin-underline` which I can't locate its repository but it is a bit more complicated and contains 120 lines of code. So I don't think in-lining it will make sense.

About the toggle, I will add it

**Comment by regevbr** [comment]
Done, can you please review?

**Comment by NGPixel** [comment]
Just not a fan of including an npm module with no public source available.

I think it would be more convenient and intuitive to use the `_word_` syntax, which the other module does.

**Comment by regevbr** [comment]
Ok, but itwill collide with current behavior causing change of ui for existing pages. If you are ok with it, I will be happy to do it

**Comment by NGPixel** [comment]
That's fine. It's an optional feature that can be turned off and almost everyone is using the `*word*` syntax for italic already. `_word_` is simply more intuitive as underline for everybody.

**Comment by regevbr** [comment]
@NGPixel I fixed it like you suggested, but I found myself duplicating the plugin code in both server and client. Is there a better way for it? (using the npm package is one way but you said you prefer not to)

**Comment by NGPixel** [comment]
Yeah it's not ideal for now, but the goal is to use the server pipeline in the future, eliminating the need to duplicate everything on the client.

**Comment by regevbr** [comment]
Thanks for the review and merge!

**Pull request merged**
