### PR TITLE
Fix toolbar z-index issue with Safari

### LINKED ISSUE #834: The Top-Left Menu Is Covered by the Menubar in Safari
### Actual behavior

The top-left menu is covered by the menubar in Safari 12.1 on macOS 10.14.4 (the latest versions as of now). Because of this, it is difficult to use since it disappears as soon as you move the cursor away from the icon.

Screenshot 2019-05-11 at 12 46 08

### Expected behavior

The menu should be above the menubar as in Firefox:

Screenshot 2019-05-11 at 12 47 52

### Steps to reproduce the behavior

1. Open an instance of Wiki.js in Safari.
2. Move the mouse over the icon for the menu in the top-left corner.

### PR DESCRIPTION
**Pull request by curieos**
This should resolve #834 

I unfortunately can't test it, the project isn't building properly on my computer. I keep getting `Error: Cannot find module './DirectoryWatcher'` or `Error: Cannot find module 'bluebird'` when I run `make docker-dev-up`

### CODE REVIEW

**Comment by NGPixel** [comment]
1. `make docker-dev-down`
1. Make sure you don't have a node_modules folder (delete it if you do).
1. `make docker-dev-rebuild`
1. `make docker-dev-up`

**Comment by curieos** [comment]
I tried that twice, I tried deleting the repo and starting from scratch, and I tried manually installing bluebird to my system (didn't work because this is a container?).

I did get these errors while building:
```warning Resolution field "core-js@3.0.0-beta.11" is incompatible with requested version "core-js@3.0.0-beta.13
warning Resolution field "core-js@3.0.0-beta.11" is incompatible with requested version "core-js@3.0.0-beta.13"
warning mathjax-node > jsdom > left-pad@1.3.0: use String.prototype.padStart()
warning passport-cas > node-uuid@1.4.1: Use uuid module instead
warning core-js@2.6.3: core-js@<2.6.5 is no longer maintained. Please, upgrade to core-js@3 or at least to actual version of core-js@2.
warning graphql-voyager > @material-ui/core > recompose > fbjs > core-js@1.2.7: core-js@<2.6.5 is no longer maintained. Please, upgrade to core-js@3 or at least to actual version of core-js@2.
warning postcss-cssnext@3.1.0: 'postcss-cssnext' has been deprecated in favor of 'postcss-preset-env'. Read more at https://moox.io/blog/deprecating-cssnext/
warning postcss-cssnext > autoprefixer > browserslist@2.11.3: Browserslist 2 could fail on reading Browserslist >3.0 config used in other tools.
warning postcss-cssnext > caniuse-api > browserslist@2.11.3: Browserslist 2 could fail on reading Browserslist >3.0 config used in other tools.
warning postcss-cssnext > pixrem > browserslist@2.11.3: Browserslist 2 could fail on reading Browserslist >3.0 config used in other tools.
warning postcss-cssnext > postcss-calc > postcss-selector-parser > flatten@1.0.2: I wrote this module a very long time ago; you should use something else.
warning postcss-cssnext > postcss-color-rebeccapurple > postcss-values-parser > flatten@1.0.2: I wrote this module a very long time ago; you should use something else.
warning postcss-preset-env > postcss-color-gray > postcss-values-parser > flatten@1.0.2: I wrote this module a very long time ago; you should use something else.
warning Resolution field "terser@3.14.1" is incompatible with requested version "terser@^3.16.1"
warning "apollo-server > apollo-server-core > apollo-tracing@0.5.2" has incorrect peer dependency "graphql@0.10.x - 14.1.x".
warning " > graphiql@0.13.0" has unmet peer dependency "prop-types@>=15.5.0".
warning "graphiql > codemirror-graphql@0.7.1" has incorrect peer dependency "graphql@^0.10.0 || ^0.11.0 || ^0.12.0 || ^0.13.0".
warning "graphiql > codemirror-graphql > graphql-language-service-parser@1.2.2" has incorrect peer dependency "graphql@^0.10.0 || ^0.11.0 || ^0.12.0 || ^0.13.0".
warning "graphiql > codemirror-graphql > graphql-language-service-interface@1.3.2" has incorrect peer dependency "graphql@^0.10.0 || ^0.11.0 || ^0.12.0 || ^0.13.0".
warning "graphiql > codemirror-graphql > graphql-language-service-parser > graphql-language-service-types@1.2.2" has incorrect peer dependency "graphql@^0.10.0 || ^0.11.0 || ^0.12.0 || ^0.13.0".
warning "graphiql > codemirror-graphql > graphql-language-service-parser > graphql-config@2.0.1" has incorrect peer dependency "graphql@^0.11.0 || ^0.12.0 || ^0.13.0".
warning "graphiql > codemirror-graphql > graphql-language-service-parser > graphql-config > graphql-import@0.4.5" has incorrect peer dependency "graphql@^0.11.0 || ^0.12.0 || ^0.13.0".
warning "graphiql > codemirror-graphql > graphql-language-service-interface > graphql-language-service-utils@1.2.2" has incorrect peer dependency "graphql@^0.10.0 || ^0.11.0 || ^0.12.0 || ^0.13.0".
warning " > postcss-cssnext@3.1.0" has unmet peer dependency "caniuse-lite@^1.0.30000697".
```

but my guess is they aren't related

When running `docker-dev-up` I get this little error though:
```  
     ❯ Build modules (1%)
    → 6 of 8 modules :: client/index-setup.js

WARNING: We noticed you're using the `useBuiltIns` option without declaring a core-js version. Currently, we assume version 2.x when no version is passed. Since this default version will likely change in future versions of Babel, we recommend explicitly setting the core-js version you are using via the `corejs` option.
```

Not sure if that has to do with anything.

**Comment by curieos** [comment]
It works. I finally figured out building. For some reason it doesn't like to build on my computer with my changes. If I build on master, then switch branches while the server is running its ok. Let me know if this is an appropriate fix for this or not. I set the z-index to 7, one below the z index of the hover menu. I couldn't find where the z-index for that is set.

Screen Shot 2019-05-13 at 3 36 39 PM

**Comment by matthew-mcallister** [comment]
I think your number is too low. See:
Screenshot_2019-05-16_09-09-04

I'm using firefox, but the dropdown menu shows as z-index 102 for me in the inspector. Maybe 100 would be a good choice for the navbar.

**Comment by curieos** [comment]
I think since the z index isn’t specified for much of the navigation the browser assigns it based on whatever rules the devs made. I’ll check this out in a bit.

**Comment by NGPixel** [comment]
Closing this PR as the issue has been fixed.

**Pull request closed without merging**
