### PR TITLE
feat: update analytics module umami

### PR DESCRIPTION
**Pull request by CDN18**
Umami has entered the next major version, introducing a breaking change to its script structure.

See: https://umami.is/docs/migrate-v1-v2

### CODE REVIEW

**Comment by NGPixel** [comment]
What if someone upgrades to the new Wiki.js version but still use v1? Will their analytics suddenly stop working?

**Comment by CDN18** [comment]
Yes, v2 and v1 are two incompatible versions.

If we want to allow users to choose between v1 and v2 themselves, we can either
- create another analysis module 
- add a setting field that allows users to enter the `script name` (`umami.js` for v1 and `script.js` for v2)

**Comment by pxlfrk** [comment]
+1 for this update - using umami in v2 & can't track my wiki page views :)

**Comment by NGPixel** [comment]
A dedicated module for v2 would be preferred. There's currently no conditional capabilities for analytic modules.

**Comment by CDN18** [comment]
Okay, I'll close this and create another one.

**Pull request closed without merging**
