### PR TITLE
Auto installer (latest branch)

### PR DESCRIPTION
**Pull request by wzrdtales**
Same as #4227 but for the latest branch

# Description 

This is an auto installer for installations in a fully automated kubernetes install. A customer needed this b/c he wants to roll it out to all the subsidiaries with the least amount of frictions possible. Since this will be useful for everyone I decided not to do an out of tree implementation.

# Notes

- `got` was added as a dependency. This project is still using request, however request is dead and deprecated for long time already. `got` is the `node.js` sides new project that fits into the spot of request best. Especially due to fine grained control over network parameters (such as socket timeouts, ssl timeouts, ...) 
- the `setup.js` file was rewritten by my auto fixer, if necessary will adjust that somewhat later, I would suggest you to add a .eslintrc or .prettierrc or both to the project to make sure that your repo standards are well defined and no one has to learn your code style standards and by that decrease interaction.
- the graphql-upload dependency was implicit, but the lock file does not get used during the build. so it was broken and added specifically

### CODE REVIEW

**Comment by NGPixel** [comment]
Please remove all the code styling changes that were made that are not specific to this PR (spaces before function params, arguments on multiple lines, etc.).

**Comment by wzrdtales** [comment]
can you please put a code style definition in your project? I really hate to waste time on CS and I don't do any, auto fixer does and it did according to your configured .eslintrc, so it did comply to the rules.

**Comment by wzrdtales** [comment]
i would on top suggest you to add something like husky to the project to make sure that code style automatically gets fixed all the time.

**Comment by wzrdtales** [comment]
small follow up @NGPixel

**Comment by wzrdtales** [comment]
little follow up again :), guess your loaded right now @NGPixel

**Comment by wzrdtales** [comment]
follow up @NGPixel

**Comment by NGPixel** [comment]
Sorry, just noticed this PR is targeting the latest branch, which is wrong. It should target the dev branch.

So either change this PR to point to dev and close your other PR, or apply the changes to your other PR and close this one.

**Comment by wzrdtales** [comment]
there is the same merge request for dev

**Comment by wzrdtales** [comment]
@NGPixel see https://github.com/Requarks/wiki/pull/4227

**Pull request closed without merging**
