### PR TITLE
feat: shortcut description box on page editor

### PR DESCRIPTION
**Pull request by ghost**
Shortcut for adding or updating a description on the page editor.
image

# Description
Originally, for medium size screens, the navigation bar's 3 components were split in size using the 12 point flex box: 
- logo: 4
- search/title 4
- settings: 4

This feature modifies the length of the logo and search/title such that: 
- logo: 2
- search/title+description: 6
- settings: 4

Thus, the settings maintain its original space, meaning that the save button will never overlap with the description box. 

For smaller screens, the navigation's components were split in 2: 
- logo: 5
- settings: 7

This was not modified, so the original mobile design is maintained. 

# Visual Examples
## Long Site Title
wiki js-description-box-long-title-demo

### Arabic
image
### French
image
### Russian
image

### <=959: title and description input not displayed
image
### Between 960 and 1263
image
### 1264 >=
image

### CODE REVIEW

**Comment by NGPixel** [comment]
- What happens if the site title is long?
- Have you tried with other languages that take more space? (e.g. "Save" in french is "Enregistrer")
- What happens on mobile or smaller screens?

**Comment by zemzot** [comment]
My bad for not including test cases earlier 😅, but hopefully your questions are answered in the updated pr!

**Review by danieldll099 — APPROVED** [review]

**Comment by zemzot** [comment]
I updated "Enter a title..." and "Enter a description..." to "Title" and "Short Description" match the page editor's placeholder text.

**Comment by zemzot** [comment]
✨

**Pull request closed without merging**
