### PR TITLE
fix: remove scss from code inside blockquote

### PR DESCRIPTION
**Pull request by uyu423**
- caused by https://github.com/requarks/wiki/discussions/5894

### screenshot

image

### CODE REVIEW

**Comment by NGPixel** [comment]
While that may fix code blocks, you're now breaking inline code. Your PR should address both, not one in favor of the other.

**Comment by uyu423** [comment]
Hi @NGPixel 

I tested the inline code markdown syntax you mentioned.
But I don't know what kind of "breaking" you're talking about.
I attach two screenshots. One is the original version, and one is my PR version.
If I missed something please tell me again

## original

image

## PR

image

**Comment by uyu423** [comment]
hi @NGPixel 

I tested the inline code markdown syntax you mentioned.
But I don't know what kind of "damage" you're talking about.
I attach two screenshots. One is the original version, and one is my PR version.

If I missed something please tell me again

### original

image

### in my PR

image

**Comment by uyu423** [comment]
@NGPixel hello?

**Comment by NGPixel** [comment]
Closing in favor of #6108

**Pull request closed without merging**
