### PR TITLE
Fix and enable OIDC auth method

### PR DESCRIPTION
**Pull request by dbnicholson**
This gets the OIDC authentication method working properly with current wiki and passport-openidconnect.

### CODE REVIEW

**Comment by benito103e** [comment]
Hi,
I tried the OIDC generic  authentication method with your fixes.
But I experienced a problem when getting authorization token :
2 requests are sent from wikijs to OIDC identity provider : 
- The first one is ok
- The second request get a 400 response with "Authorization code has been revoked" error
Did you already experience the same issue ?

**Comment by benito103e** [comment]
It's ok if I skip user profile : `skipUserProfile: true,`
So I don't have the same behaviour than you and I need to instantiate user with : 

```
const user = await WIKI.models.users.processProfile({
            profile: {
              id: jwtClaims.sub,
              email: _.get(jwtClaims, 'email'),
              name: _.get(jwtClaims, 'name')
            },
            providerKey: 'oidc'
          })
```

**Comment by dbnicholson** [comment]
No that didn't happen for me. Does your provider normally allow requesting the user profile? Does it support the `profile` scope? Is your client doing a `code` flow or an `id_token` flow?

I suppose `skipUserProfile` could be an option and you would attempt to get the info from the id token claims like this.

**Comment by benito103e** [comment]
Yes I think skipUserProfile option is required.
Because the retrieval of user profile data is not part of OIDC core.

And it is one of the possible options in the passport-openidconnect (identifierField, scope, passReqToCallback, skipUserProfile, sessionKey, store, authorizationURL, tokenURL).

We should also keep emailClaim and usernameClaim options to extract them from IdToken.

**Comment by dbnicholson** [comment]
`usernameClaim` to me implies an actual username but wiki uses the email address for a username. I think `nameClaim` would be clearer, but I don't feel that strongly about it.

My reading of the oidc spec is that for the `code` flow that provides an access token, the userinfo endpoint should be accessible - https://openid.net/specs/openid-connect-core-1_0.html#ScopeClaims. However, I don't see any reason to keep that option out of you know the id token contains all the necessary claims.

**Comment by benito103e** [comment]
I totally agree with you on naming nameClaim.

you're right about "UserInfo Endpoint" : this is described in core specs but it's frequently considered optional and we should have all data we need in IDToken.

**Comment by NGPixel** [comment]
Thanks 👍

**Comment by dbnicholson** [comment]
@NGPixel thanks. @benito103e I'll try to get a little time this week to open another PR to address the comments we discussed.

**Pull request merged**
