### PR TITLE
docs: Added demo possibility

### PR DESCRIPTION
**Pull request by belokonm**
This PR adds Runme button-label [Runme](https://runme.io/run?app_id=5681a667-6687-40e1-b6be-f543e6803ef0) (forked on cloned repo) to run the project from latest commit with one click.

**How it works:**
1. Runme clones the repository and builds a docker image for latest commit;
2. deploys docker image to k8s cluster;
3. creates domain with SSL certificate;
4. shows web application;
5. destroys app instance after 10 minutes.

You can find detailed information on how this works [here](https://runme.io/how-it-works). The small demo you can find [here](https://www.youtube.com/channel/UCEysV237wo321JatUTC6Rlg).

**Why we suggest this?**
- Runme is perfect solution to demonstrate current state of code/repository, anybody can just click the button and see the state;
- Runme totally free, we love open source projects and want to support them;
- Runme has only one limit: you can run one commit no more than once every 5 minutes;

Result will looks like : 
image

### CODE REVIEW

**Comment by NGPixel** [comment]
Thanks for the suggestion! I created a new config.yaml to use postgres instead of mysql and created a page in the docs with detailed info:
https://docs.requarks.io/demo

**Comment by rathax** [comment]
Does not work anymore

**Comment by NGPixel** [comment]
Fixed.

**Comment by remisharrock** [comment]
hello, looks like the link to the demo doesn't work : 
https://runme.io/run?app_id=5ad463aa-078d-4471-aac9-199dc41ed896

Oops!
No app has been found with ID "5ad463aa-078d-4471-aac9-199dc41ed896. Please (re)generate a new button in order to run your application. Please go back to the generator page and create a button and run url

**Pull request closed without merging**
