### PR TITLE
fix: resolve admin pages pagination bug

### PR DESCRIPTION
**Pull request by tsh96**
Solve Admin Search bug #1180

### CODE REVIEW

**Review by NGPixel — APPROVED** [review]

**Comment by craph** [comment]
Hi @tsh96 ,
I was looking your PR because I'm trying to increase my skills to contribute to this beautiful project and I'm unable to understand what does the `@page-count="pageTotal = $event"` 
I'm not familliar with this synthax for vuejs I think it's pug in a vue template but I'm not aware of what the `@` does 

Please could you give me some advise ?
Thank you very much.

Best regards,

**Comment by NGPixel** [comment]
`@something` is an event in Vue.js. So when event `page-count` is triggered by the component, the expression in quotes is evaluated. In this case, the variable `pageTotal` is updated with the value of $event.

**Comment by craph** [comment]
@NGPixel Thank you very much for the explanation :) 
So if I'm right `@something` is an event and `:something` is a property of the component where it's placed ?

**Comment by tsh96** [comment]
Hi @craph, 
Yes, 
`@` is shorthand for `v-on:` which is used to handle an event.
`:` is shorthand for `v-bind:` which is used to bind a data.

Another well known shorthand is `#` for `v-slot:`

For more information you can refer to 
https://vuejs.org/v2/guide/syntax.html#Shorthands
https://vuejs.org/v2/api/#v-slot

**Comment by craph** [comment]
> Hi @craph, Yes, `@` is shorthand for `v-on:` which is used to handle an event. `:` is shorthand for `v-bind:` which is used to bind a data.
> 
> Another well known shorthand is `#` for `v-slot:`
> 
> For more information you can refer to https://vuejs.org/v2/guide/syntax.html#Shorthands https://vuejs.org/v2/api/#v-slot

Thank you very much @tsh96 :)

**Pull request merged**
