### PR TITLE
feat: Page Properties should allow switching template type #1186

### PR DESCRIPTION
**Pull request by regevbr**
fix: #1186

Implement editor changing after page creation.
The implementation ~is pretty straight forward and~ works all ways.
@NGPixel I'm not a UI/UX man so please let me know what changes you want to make.
Also this is my first real time working with vue so excuse my beginners mistakes if such exists

### CODE REVIEW

**Comment by regevbr** [comment]
wiki

**Comment by regevbr** [comment]
My only drawback is the file extension. Do we need to change it when the editor is changed?
If we don't change it, it might affect auto importing from remote sources (like git)

**Comment by regevbr** [comment]
Not renaming the file can cause issues when moving pages around, as the storage modules calculate the path using the file name extension which can be changed.
I need to fire the renamed event to the storage module when the content type of a page is changed (markdown -> code for example).
Also need to modify the storage modules `renamed` event handle to be able to get the current and new file extension, as the current implementation will fail.
@NGPixel thoughts?

**Comment by regevbr** [comment]
I added code to handle the renaming of the file, works well. The PR is ready for CR

**Comment by NGPixel** [comment]
There's also the matter of converting markdown to HTML and vice-versa when switching editors.

For the renaming situation, I think a new event type altogether would be more appropriate. It may call the standard rename under the hood, but that would allow for more flexibility in storage modules instead of trying to make `rename` handle everything.

**Comment by regevbr** [comment]
@NGPixel thanks for the comments.

About the conversion:
1. From html to markdown we can use https://github.com/domchristie/turndown
2. From markdown to html - can we simply use the rendered html? are there any drawbacks to using it?

About the renaming event:
If you take a look at the code you will see it is not adding any complexity...  The method already has a source/target for most properties, so I just added the extensionType to the mix. Making a new event will be a simple pass through function and the same changes will be required for the existing renamed methods. thoughts?

**Comment by regevbr** [comment]
I implement the type conversion - see gif below.

wiki3

**Comment by regevbr** [comment]
@NGPixel did you have a chance to look at this PR?

**Comment by NGPixel** [comment]
Change target branch to `dev` for this PR.

**Pull request closed without merging**
