### PR TITLE
Editor WYSIWYG and Videos: Improving/Fixing "Insert Media"

### PR DESCRIPTION
**Pull request by KingRial**
When using WYSISYG editor with "Insert media" button, the inserted video was not visible on view mode (See: https://github.com/Requarks/wiki/issues/1459)

Modified code to:

- handle issue https://github.com/Requarks/wiki/issues/1459
- support also video URLs from inside wiki.js uploaded assets

**NB** Iframes must be enabled otherwise embedding external videos (Eg. Youtube video) is not possible ^^
image

### CODE REVIEW

**Comment by NGPixel** [comment]
Change target branch to `dev` for this PR.

**Comment by Jhobean** [comment]
This commit work? I need this functionnality.:cry:

**Comment by KingRial** [comment]
@Jhobean It works (and it can be improved too!).

I am slowly improving standard video support and will share the improvements if current PR reaches a stable release.

If you are curious you can check the little improvements here:
- Better Regexp to support special characters too ([here](https://github.com/Clevermind-Think-Mint/wiki/blob/Mr.Ally_2.5.144/client/components/editor/editor-ckeditor.vue#L94))
- Ability to add an uploaded local video to the page by simply pressing the "Insert asset" ([here](https://github.com/Clevermind-Think-Mint/wiki/blob/Mr.Ally_2.5.144/client/components/editor/editor-ckeditor.vue#L117) and [here](https://github.com/Clevermind-Think-Mint/wiki/blob/Mr.Ally_2.5.144/client/components/editor/editor-modal-media.vue#L364))

**Comment by Jhobean** [comment]
Thx KingRial, I'm not a programmer :-( don't really undestand all these line :-) . But i'm Happy to see you work on it. You'll probably push a new PR soon to NGPixel. Thx for your contribution.

This feature of embeded Vidéo on wiki is a Major feature I need on my wiki.

**Comment by Kaibert123** [comment]
@KingRial I went through the Administrator stuff, and could not find the option to allow iframes - there was a block iframes option, and I toggled that off, but did not fix the issue.

**Comment by KingRial** [comment]
Hi @Kaibert123,

as you can see my work has not met the interest of the main project and has not be merged.
The current pull request is so old that problably won't be anymore compatible with current stable release.

**Comment by nasiralamreeki** [comment]
> Hi @Kaibert123,
> 
> 
> 
> as you can see my work has not met the interest of the main project and has not be merged.
> 
> The current pull request is so old that problably won't be anymore compatible with current stable release.

That's very unfortunate that @NGPixel didn't at-least give feedback.

**Comment by dotesfera** [comment]
Also this does not work for me. Is there any progress on this?

**Comment by whotakekajibu** [comment]
How about the progress?

**Comment by grahamgraham** [comment]
I've added some info in this discussion (https://github.com/requarks/wiki/discussions/3099). 
It is not fixed as of 2.5.305. 
@NGPixel Can we please reopen this issue?

**Pull request closed without merging**
